#!/bin/dash
#https://forums.linuxmint.com/viewtopic.php?t=369909
# Kill if already running

#if pidof -o %PPID -x "${0##*/}"; then
#  exit 1
#fi
# Start loop

# Calculate approximate moon phase
#https://gist.githubusercontent.com/Crysknife007/29b00826c86b9a91945ce6e4efccc2b5/raw/ea8b75f0bb050acb9a20523fd4d9b00d9ae1cfb3/moonphase.sh

moonphase(){

  local lp=2551443
  local now=$(date -u +"%s")
  local newmoon=592500
  local phase=$((($now - $newmoon) % $lp))
  local phase_number=$((((phase / 86400) + 1)*100000))

  # Multiply by 100000 so that we can do integer comparison in bash.
  if   [ $phase_number -lt 184566 ];   then phase_icon="○ New"            
  elif [ $phase_number -lt 553699 ];   then phase_icon="❩ Waxing Crescent" 
  elif [ $phase_number -lt 922831 ];   then phase_icon="◗ First Quarter"  
  elif [ $phase_number -lt 1291963 ];  then phase_icon="◑ Waxing Gibbous"  
  elif [ $phase_number -lt 1661096 ];  then phase_icon="● Full"            
  elif [ $phase_number -lt 2030228 ];  then phase_icon="◐ Waning Gibbous"  
  elif [ $phase_number -lt 2399361 ];  then phase_icon="◖ Last Quarter"    
  elif [ $phase_number -lt 2768493 ];  then phase_icon="❨ Waning Crescent" 
  else
                                            phase_icon="○ New"             
  fi

  # Get the current phase day
  number=$(($phase_number/100000));

  # Echo the current Moon Phase Icon, name, and day number
  echo $phase_icon Moon. Day $number

}

      moonphase;
while :
do
# What time is it?
  CURRENT_TIME=$(date +%H%M)
  if [ -n "$NEXT_TIME" ] && [ "$CURRENT_TIME" -lt "$NEXT_TIME" ]; then
    sleep 60
    continue
  fi
# Depending on time set THEME_CHOICE & NEXT_TIME
  if [ "$CURRENT_TIME" -ge 0000 ] && [ "$CURRENT_TIME" -lt 0420 ]; then
    THEME_CHOICE=BlackMATE
    THEME_CHOICE2=custom1
    WALL_CHOICE=/ubuntu2_by_arman1992.jpg
    WALL_CHOICE2=/284466.jpg
    NEXT_TIME=0420
  elif [ "$CURRENT_TIME" -ge 0420 ] && [ "$CURRENT_TIME" -lt 0630 ]; then
    THEME_CHOICE=BlackMATE
    THEME_CHOICE2=custom1
    WALL_CHOICE=/DSC2943_by_kcpru.jpg
    WALL_CHOICE2=/1939285.jpg
    NEXT_TIME=0630
  elif [ "$CURRENT_TIME" -ge 0630 ] && [ "$CURRENT_TIME" -lt 1600 ]; then
    THEME_CHOICE=BlackMATE
    THEME_CHOICE2=custom1
    WALL_CHOICE=/DSC2943_by_kcpru.jpg
    WALL_CHOICE2=/1939285.jpg
    NEXT_TIME=1600
  elif [ "$CURRENT_TIME" -ge 1600 ] && [ "$CURRENT_TIME" -le 2359 ]; then
    THEME_CHOICE=BlackMATE
    THEME_CHOICE2=custom1
    #BlackMATE
    WALL_CHOICE=/blue-marble-west.jpg
    WALL_CHOICE2=/macos-mojave-night-wallpaper-preview.jpg
    NEXT_TIME=0000
  fi
  
# Set the chosen theme
  #gsettings set org.cinnamon.desktop.interface gtk-theme "$THEME_CHOICE"
  #gsettings set org.cinnamon.theme name "$THEME_CHOICE"
  #gsettings set org.cinnamon.desktop.wm.preferences theme "$THEME_CHOICE"
  #gsettings set org.cinnamon.desktop.background picture-uri "file://$WALL_CHOICE"
 
    if (( $1 )) ; then
        dconf write /org/mate/desktop/background/picture-filename "\"$PWD/""$WALL_CHOICE2\""
        #dconf write /org/mate/marco/general/theme "\"$THEME_CHOICE\"" Yaru
        dconf write /org/mate/desktop/interface/gtk-theme "\"$THEME_CHOICE2\""
    else
        dconf write /org/mate/desktop/background/picture-filename "\"$PWD/""$WALL_CHOICE\""
      #  dconf write /org/mate/desktop/interface/gtk-theme "\"$THEME_CHOICE\""   
        #dconf write /org/mate/desktop/interface/icon-theme "'Suru'"
        #dconf write /org/mate/desktop/peripherals/mouse/cursor-theme "'crystalgray'"
    fi
# Sleep
  sleep 600
done
